// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ActivateWindow():Promise<void>;

export function ClearPinnedFingerprint(arg1:string):Promise<void>;

export function ConnectClient(arg1:config.ClientConfig):Promise<string>;

export function ConsumePendingImport():Promise<Record<string, any>>;

export function ExportConfig(arg1:config.ClientConfig):Promise<string>;

export function GetClientVersion():Promise<string>;

export function GetHealth():Promise<Record<string, any>>;

export function GetPinnedFingerprint(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HandleRemoteImport(arg1:Array<string>):Promise<void>;

export function HasPinnedFingerprint(arg1:string):Promise<boolean>;

export function ImportConfigDialog():Promise<config.ClientConfig>;

export function ImportConfigFile(arg1:string):Promise<config.ClientConfig>;

export function IsFileAssociationRegistered():Promise<boolean>;

export function IsQuitting():Promise<boolean>;

export function QuitFromTray():Promise<void>;

export function RegisterFileAssociation():Promise<void>;

export function SetQuitting(arg1:boolean):Promise<void>;

export function SetStartupArgs(arg1:Array<string>):Promise<void>;

export function ShowWindowFromTray():Promise<void>;

export function Stop():Promise<void>;

export function ToggleConnectionFromTray():Promise<void>;

export function ToggleWindowVisibility():Promise<void>;
