// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateWindow() {
  return window['go']['main']['App']['ActivateWindow']();
}

export function ClearPinnedFingerprint(arg1) {
  return window['go']['main']['App']['ClearPinnedFingerprint'](arg1);
}

export function ConnectClient(arg1) {
  return window['go']['main']['App']['ConnectClient'](arg1);
}

export function ConsumePendingImport() {
  return window['go']['main']['App']['ConsumePendingImport']();
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetClientVersion() {
  return window['go']['main']['App']['GetClientVersion']();
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetPinnedFingerprint(arg1) {
  return window['go']['main']['App']['GetPinnedFingerprint'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleRemoteImport(arg1) {
  return window['go']['main']['App']['HandleRemoteImport'](arg1);
}

export function HasPinnedFingerprint(arg1) {
  return window['go']['main']['App']['HasPinnedFingerprint'](arg1);
}

export function ImportConfigDialog() {
  return window['go']['main']['App']['ImportConfigDialog']();
}

export function ImportConfigFile(arg1) {
  return window['go']['main']['App']['ImportConfigFile'](arg1);
}

export function IsFileAssociationRegistered() {
  return window['go']['main']['App']['IsFileAssociationRegistered']();
}

export function IsQuitting() {
  return window['go']['main']['App']['IsQuitting']();
}

export function P2PPaths() {
  return window['go']['main']['App']['P2PPaths']();
}

export function P2PReasonText(arg1) {
  return window['go']['main']['App']['P2PReasonText'](arg1);
}

export function P2PTrafficNote() {
  return window['go']['main']['App']['P2PTrafficNote']();
}

export function PunchSessionState(arg1) {
  return window['go']['main']['App']['PunchSessionState'](arg1);
}

export function PunchTo(arg1) {
  return window['go']['main']['App']['PunchTo'](arg1);
}

export function QuitFromTray() {
  return window['go']['main']['App']['QuitFromTray']();
}

export function RegisterFileAssociation() {
  return window['go']['main']['App']['RegisterFileAssociation']();
}

export function SetP2PLocal(arg1) {
  return window['go']['main']['App']['SetP2PLocal'](arg1);
}

export function SetQuitting(arg1) {
  return window['go']['main']['App']['SetQuitting'](arg1);
}

export function SetStartupArgs(arg1) {
  return window['go']['main']['App']['SetStartupArgs'](arg1);
}

export function ShowWindowFromTray() {
  return window['go']['main']['App']['ShowWindowFromTray']();
}

export function SignalQuery(arg1) {
  return window['go']['main']['App']['SignalQuery'](arg1);
}

export function SignalSelf() {
  return window['go']['main']['App']['SignalSelf']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleConnectionFromTray() {
  return window['go']['main']['App']['ToggleConnectionFromTray']();
}

export function ToggleWindowVisibility() {
  return window['go']['main']['App']['ToggleWindowVisibility']();
}
